### ISSUE TITLE
How to format Function Documentation

### ISSUE THREAD

**Issue by taylorh140** [symmetryinvestments/excel-d#71]
After registering a function some times the text for the function arguments is not pretty:
![image](https://user-images.githubusercontent.com/10996543/57319143-8bebdb80-70c1-11e9-8832-be97b839e229.png)

![image](https://user-images.githubusercontent.com/10996543/57319127-82627380-70c1-11e9-82b7-41ad1dbf7f3a.png)

I used the following information for Registry:
@Register(ArgumentText("Find A subset from the list which sums to specified value"w),
          HelpTopic("Find A subset from the list which sums to specified value"w),
          FunctionHelp("Find A subset from the list which sums to specified value"w),
          ArgumentHelp(["List, contains list where subsets reside"w,"TargetValue, Goal Value for subset"w,"MaxListSize, Maximum number of subset items allowed (this makes a very large difference in calcualtion time)"w]))

I suppose what I need here is documentation on what goes where and how to format it.

Thanks!

**Comment by atilaneves** [comment]
Thanks for filing the issue. How did you get the dialogs about function arguments in Excel?

**Comment by taylorh140** [comment]
I use the fx button :)
![Fxarg](https://user-images.githubusercontent.com/10996543/57629002-9e9e5e80-7560-11e9-8529-aab6ce80fd61.gif)
I have Excel 2016 but I think the layout is mostly the same for previous versions.

**Comment by Laeeth** [comment]
It's a known bug in Excel.
https://docs.microsoft.com/en-us/office/client-developer/excel/known-issues-in-excel-xll-development

**Comment by adamdruppe** [comment]
Working around the Excel bug is simple in the wrapper. It seems the ArgumentsText thing is actually a semicolon-separated list of argument names.

HelpTopic also has a specific format involving a !. I'll add some code comments in a PR at least.

**Comment by adamdruppe** [comment]
https://github.com/symmetryinvestments/excel-d/pull/81

**Comment by atilaneves** [comment]
Closed by https://github.com/symmetryinvestments/excel-d/pull/81

**Comment by adamdruppe** [comment]
leaving this as a note to self but it might be a good idea to hard-code the install path of the excel sdk for linking instead of having to hunt down the lib

(the stupid eula prohibits redistribution, but linking to and having the path known to the default build script can be the next best thing for a smooth "just works" experience)
