### ISSUE TITLE
docs folder contains colliding file

### ISSUE THREAD

**Issue by Geod24** [symmetryinvestments/excel-d#84]
```
Cloning into 'excel-d'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 3739 (delta 14), reused 23 (delta 9), pack-reused 3699
Receiving objects: 100% (3739/3739), 981.46 KiB | 1.26 MiB/s, done.
Resolving deltas: 100% (2399/2399), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'docs/xlld.any.Any.html'
  'docs/xlld.any.any.html'
  'docs/xlld.memorymanager.AllocatorContext.html'
  'docs/xlld.memorymanager.allocatorContext.html'
  'docs/xlld.wrap.traits.DllDefFile.html'
  'docs/xlld.wrap.traits.dllDefFile.html'
  'docs/xlld.wrap.traits.GenerateDllDef.html'
  'docs/xlld.wrap.traits.generateDllDef.html'
```

This triggers on any case-insensitive filesystem (I'm on a Mac OSX 10.15)

**Comment by atilaneves** [comment]
This happens on Windows as well. I'd never figured out why. If anything I'd say this is a adrdox issue.

**Comment by adamdruppe** [comment]
D symbol names are case sensitive and the doc generator uses the D symbol name as the doc file name....

I sometimes forget people use terrible operating systems with inferior file systems. idk it could generate them differently but it is a hassle.

**Comment by atilaneves** [comment]
> D symbol names are case sensitive and the doc generator uses the D symbol name as the doc file name....
> 
> I sometimes forget people use terrible operating systems with inferior file systems. idk it could generate them differently but it is a hassle.

I understand *why* adrdox is doing that, but people need to use Windows, especially if they're using excel-d.

**Comment by adamdruppe** [comment]
On Tue, Feb 04, 2020 at 07:37:51AM -0800, Atila Neves wrote:
> I understand *why* adrdox is doing that, but people need to use Windows, especially if they're using excel-d.

yeah most the link generation is encapsulated in a single function
so i could probably make a new command line switch to do something
different.

I just need to determine what it should do. Maybe just stick a hash
at the end to disambiguate or prefix caps with _ or something like that.

added a `--case-insensitive-filenames` command line arg to do the
prefix thing as a quick fix.
