### ISSUE TITLE
Don't uppercase the first character of function names

### ISSUE THREAD

**Issue by rmanthorpe** [symmetryinvestments/excel-d#89]
> excel-d will always convert the first character in the D function being wrapped to uppercase since that is the Excel convention.

This convention is often broken on purpose by Excel add-ins (along with having a common prefix for all functions) to make it clear that the function is not part of the standard Excel functions. It's just a little visual queue that many find helpful. Perhaps this could be decided with a version instead for backward compatibility.

**Comment by atilaneves** [comment]
Wouldn't it be better for this to be an option that the user can specify?

**Comment by rmanthorpe** [comment]
Yes, that's why I suggested a version, so you can compile with `version(NoUpperCase)` or something. All or nothing struck me as the right level or granularity - after all the users have control over the code they're wrapping so if they want a mixture they can do it by hand. Now that I think about it another flag for `wrapAll` might be a better choice!
